# Generated by Django 3.2.9 on 2021-11-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('parent_picture', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
