# Generated by Django 3.2.9 on 2021-11-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_resizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='media', width_field='width'),
        ),
    ]
